# -*- coding: utf-8 -*-
# Deployment settings for HeyBox2D.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/6.3/s3e/makefile_builder/mkb.py', 'v:/GigglingBits/box2d/HeyBox2D/HeyBox2D.mkb', '--default-buildenv=vc11', '--msvc-project', '--deploy-only']
mkb = 'v:/GigglingBits/box2d/HeyBox2D/HeyBox2D.mkb'
mkf = ['c:\\marmalade\\6.3\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\6.3\\modules\\legacy\\iw2d\\iw2d_legacy.mkf', 'c:\\marmalade\\6.3\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\6.3\\modules\\legacy\\iwgx\\iwgx_legacy.mkf', 'c:\\marmalade\\6.3\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\6.3\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\6.3\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\6.3\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\6.3\\modules\\third_party\\zlib\\zlib.mkf', 'c:\\marmalade\\6.3\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\6.3\\modules\\legacy\\iwresmanager\\iwresmanager_legacy.mkf', 'c:\\marmalade\\6.3\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\6.3\\modules\\iwgxfont\\iwgxfont.mkf', 'c:\\marmalade\\6.3\\modules\\legacy\\iwgxfont\\iwgxfont_legacy.mkf', 'c:\\marmalade\\6.3\\modules\\third_party\\tiniconv\\tiniconv.mkf', 'c:\\marmalade\\6.3\\examples\\examplescore\\examplescore.mkf', 'v:\\gigglingbits\\box2d\\box2d.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('v:/GigglingBits/box2d/HeyBox2D/data/Image.png', 'Image.png', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'HeyBox2D'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'HeyBox2D'
    long_caption = 'HeyBox2D'
    version = [0, 0, 1]
    config = ['v:/GigglingBits/box2d/HeyBox2D/data/app.icf']
    data_dir = 'v:/GigglingBits/box2d/HeyBox2D/data'
    iphone_link_lib = []
    linux_ext_lib = []
    android_extra_application_manifest = []
    iphone_link_libdir = []
    iphone_link_libdirs = []
    splashscreen = 'c:/marmalade/6.3/examples/resources/splashscreens'
    iphone_link_opts = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    win32_ext_dll = []
    android_so = []
    osx_ext_dll = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'v:/GigglingBits/box2d/HeyBox2D/build_heybox2d_vc11/Debug_HeyBox2D_VC11_gcc_x86/HeyBox2D.so',
                   'release' : r'v:/GigglingBits/box2d/HeyBox2D/build_heybox2d_vc11/Release_HeyBox2D_VC11_gcc_x86/HeyBox2D.so',
                 },
         'mips_gcc' : {
                   'debug'   : r'v:/GigglingBits/box2d/HeyBox2D/build_heybox2d_vc11/Debug_HeyBox2D_VC11_gcc_mips/HeyBox2D.so',
                   'release' : r'v:/GigglingBits/box2d/HeyBox2D/build_heybox2d_vc11/Release_HeyBox2D_VC11_gcc_mips/HeyBox2D.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'v:/GigglingBits/box2d/HeyBox2D/build_heybox2d_vc11/Debug_HeyBox2D_VC11_gcc_arm/HeyBox2D.s3e',
                   'release' : r'v:/GigglingBits/box2d/HeyBox2D/build_heybox2d_vc11/Release_HeyBox2D_VC11_gcc_arm/HeyBox2D.s3e',
                 },
         'mips' : {
                   'debug'   : r'v:/GigglingBits/box2d/HeyBox2D/build_heybox2d_vc11/Debug_HeyBox2D_VC11_gcc_mips/HeyBox2D.so',
                   'release' : r'v:/GigglingBits/box2d/HeyBox2D/build_heybox2d_vc11/Release_HeyBox2D_VC11_gcc_mips/HeyBox2D.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'v:/GigglingBits/box2d/HeyBox2D/build_heybox2d_vc11/Debug_HeyBox2D_VC11_gcc_x86_android/HeyBox2D.so',
                   'release' : r'v:/GigglingBits/box2d/HeyBox2D/build_heybox2d_vc11/Release_HeyBox2D_VC11_gcc_x86_android/HeyBox2D.so',
                 },
         'arm' : {
                   'debug'   : r'v:/GigglingBits/box2d/HeyBox2D/build_heybox2d_vc11/Debug_HeyBox2D_VC11_arm/HeyBox2D.s3e',
                   'release' : r'v:/GigglingBits/box2d/HeyBox2D/build_heybox2d_vc11/Release_HeyBox2D_VC11_arm/HeyBox2D.s3e',
                 },
         'x86' : {
                   'debug'   : r'v:/GigglingBits/box2d/HeyBox2D/build_heybox2d_vc11/Debug_HeyBox2D_VC11_x86/HeyBox2D.s86',
                   'release' : r'v:/GigglingBits/box2d/HeyBox2D/build_heybox2d_vc11/Release_HeyBox2D_VC11_x86/HeyBox2D.s86',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
